### ISSUE TITLE
Add the conversation average rate at the customer profile in Intercom

### ISSUE THREAD

**Issue by shid** [hostinger/brazil#8]
#### What we need
Add at the customer profile the avg of the conversation rate as shown at the image http://prntscr.com/j9lpu1

This information is relevant to the agent to be aware and if the avg is low, the agent should give a special treat to the customer.

#### Suggestion to implement that
1. Create a new field like `customer_id` at the `intercom_conversation_ratings` table;
2. Send the avg rate at hpanel to this intercom variable `avg_rate` http://prntscr.com/jd9z73 like this issue https://github.com/hostinger/marketing/issues/606

**Comment by prodigeris** [comment]
@dgbox

**Comment by dgbox** [comment]
@samuelweblink don't you think we need to see this issue on a global scale? Start hiring new agents, try to increase the quality part and no one will need to check this "parameter". I think we should treat all clients with lots of love, not just create a mindset for the agents to special treat the ones with lower avg. I don't like this idea. Maybe in CRM it's good to see overview of the client, but not for the intercom.

@rodrigowiethorn can we stop creating/pushing tasks which are not aligned globally first?

**Comment by rodrigowiethorn** [comment]
@dgbox i got your point... make sense treat all the customers with the same love, but some customers are way difficult than others, and treat everyone equal is kind of hard, because no one is equal... [even twins](https://www.nytimes.com/2004/11/02/health/the-claim-identical-twins-have-identical-fingerprints.html)... 😜

As we saw on [Brendon's email](http://prntscr.com/jdrc8f) about the BAD RATE project on Intercom, around 7% of our customers evaluate us bad. If 7% of our 34,3k paying customers (~2,2k) are in a bad mood we could loose a lot of money, and matter of act, we've been doing like that... our churn is just huge ~42%.

So in order to fulfill our OKR "We are No. 1 Customer centric company" and make customers love us, i guess will be a good move let agents know when they're facing an unhappy customer, because they can prepare themselves to give a better experience to these guys.

Allow me disagree from you when you said "can we stop creating/pushing tasks which are not aligned globally first?"... we're doing everything according Global OKR. We also prepare a list of enhancements people suggested down here, and all of those are into [BR DEV TEAM Project](https://github.com/orgs/hostinger/projects/15).

Did @shid introduce it to you? What do you think?

Best

**Comment by shid** [comment]
I send the Lineup BR DEV Project on the [#success-dev channel on slack ](https://hostinger.slack.com/archives/CA4ESRB39/p1523881858000375)
But @dgbox would be good to check it or we can schedule a meeting to we discuss those features to be implementeded.

**Comment by samuelweblink** [comment]
@dgbox Following your comments, we discussed the isuue here and decided to keep it off for now, until we have the opportunity to talk together about it and discuss its benefits/drawbacks.
