### ISSUE TITLE
Balance of clients

### ISSUE THREAD

**Issue by dgbox** [hostinger/brazil#9]
@samuelweblink can you check who is responsible for doing such kinda refunds on client profiles? Why they are negative after that? Can you make the corrections to 0?

You can find them in CRM by client ID

[negative_balance.csv.zip](https://github.com/hostinger/brazil/files/1973734/negative_balance.csv.zip)

**Comment by samuelweblink** [comment]
@dgbox @laiand @vaidas-lungis @4Giedrius In BR, some payments may take up to 72 business hours to be received/confirmed by our systems. On those cases, if client sends us proof of payment, we activate account, and make their balance negative (equal to the amount of the payment to be confirmed) so that when the payment is received, it will cover the negative balance and they won't have wrong credits on their balance. Until little time ago, this was not made by Customer Success - we have responsible guys checking all accounts right now - will update info as soon as we are done.

**Comment by Joserigon** [comment]
@dgbox @laiand @vaidas-lungis @4Giedrius All balances in BRL have been analyzed and successfully reset. Some transactions were paid, however, they were not identified by the system.

**Comment by dgbox** [comment]
thank you
